# fly.toml app configuration file for PigeonHub
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pigeonhub'
primary_region = 'iad'

[build]
  builder = 'heroku/buildpacks:20'

[env]
  APP_ID = 'GLOBAL-PEERPIGEON-HUB'
  MAX_PEERS = '100'
  PORT = '8080'
  REGION = 'us-east'
  SEED_PUBLIC_KEY = 'MCowBQYDK2VwAyEAdn9neC3tVRDmYgvHGOtP164K01xwrHEitu3HAWg403k='
  SEED_SIGNATURE = ''

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
